Ndim_ :=    4   :
x1_    :=    r   :
x2_    :=    theta   :
x3_    :=    phi   :
x4_    :=    t   :
sig_:=2:
g11_    :=    1/((1-2*m/r))   :
g22_    :=  r^2   :
g33_    :=    r^2*sin(theta)^2  :
g44_    :=    (-1+2*m/r)   :
Info_:=`The Schwarzschild metric in curvature coordinates`:
